name: applicant_assignments
description: Applicant Assignment for zucol
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  flutter_event_calendar: ^1.0.0
  scrollable_positioned_list: ^0.3.8
  get: ^4.6.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/Quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/Quicksand/static/Quicksand-SemiBold.ttf
          weight: 600
